/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jifPessoas.java
 *
 * Created on 02/04/2009, 19:33:36
 */

package br.pro.luciene.ProjetoVendas.view;


import br.pro.luciene.ProjetoVendas.data.PessoaData;
import br.pro.luciene.ProjetoVendas.data.SituacaoData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import br.pro.luciene.ProjetoVendas.model.Cliente;
import br.pro.luciene.ProjetoVendas.model.Fornecedor;
import br.pro.luciene.ProjetoVendas.model.Funcionario;
import br.pro.luciene.ProjetoVendas.model.Pessoa;
import br.pro.luciene.ProjetoVendas.model.Situacao;
import br.pro.luciene.ProjetoVendas.model.Telefone;
import java.sql.Timestamp;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Diretor
 */
public class jifFuncionarios extends javax.swing.JInternalFrame {
    Cliente objCli;
    Funcionario objFun;
    Fornecedor objForn;
    Vector <Telefone> vetortelefones;
    Vector <Situacao> vetorSituacoes;
    PessoaData DAO;
    SituacaoData DAOSituacao;
    Vector cabecalho;
    /** Creates new form jifPessoas */
    public jifFuncionarios() {
        initComponents();
        try {
            objCli = new Cliente();
            objFun = new Funcionario();
            objForn=new Fornecedor();
            vetortelefones = new Vector<Telefone>();
            vetorSituacoes = new Vector<Situacao>();
            cabecalho = new Vector(); //JTable Pesquisa
            DAO = new PessoaData();
            DAOSituacao = new SituacaoData();
            vetorSituacoes = DAOSituacao.carregarCombo();
            jcbSituacao.setModel(new 
                DefaultComboBoxModel(vetorSituacoes));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "Erro ao abrir: " +
                    e.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jbConsultar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jlCodigo = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jlEmail = new javax.swing.JLabel();
        jtEmail = new javax.swing.JTextField();
        jtId = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbTelefones = new javax.swing.JTable();
        jbRetirar = new javax.swing.JButton();
        jlTelefones = new javax.swing.JLabel();
        jcTipo = new javax.swing.JComboBox();
        jtDDD = new javax.swing.JTextField();
        jtTelefone = new javax.swing.JTextField();
        jbAdicionar = new javax.swing.JButton();
        jlEmail2 = new javax.swing.JLabel();
        jtEndereco = new javax.swing.JTextField();
        jlEmail3 = new javax.swing.JLabel();
        jtBairro = new javax.swing.JTextField();
        jlEmail4 = new javax.swing.JLabel();
        jtNumero = new javax.swing.JTextField();
        jlEmail5 = new javax.swing.JLabel();
        jtComplemento = new javax.swing.JTextField();
        jlDataCadastro = new javax.swing.JLabel();
        jtCidade = new javax.swing.JTextField();
        jftCep = new javax.swing.JFormattedTextField();
        jlEmail7 = new javax.swing.JLabel();
        jlEmail8 = new javax.swing.JLabel();
        jcbUf = new javax.swing.JComboBox();
        jcbSituacao = new javax.swing.JComboBox();
        jlEmail9 = new javax.swing.JLabel();
        jlEmail10 = new javax.swing.JLabel();
        jlEmail11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtCTPS = new javax.swing.JTextField();
        jlContato = new javax.swing.JLabel();
        jlEmail1 = new javax.swing.JLabel();
        jpfSenha = new javax.swing.JPasswordField();
        jlCnpj4 = new javax.swing.JLabel();
        jtRGFuncionario = new javax.swing.JTextField();
        jlIe7 = new javax.swing.JLabel();
        jftCPFFuncionario = new javax.swing.JFormattedTextField();
        jlIe4 = new javax.swing.JLabel();
        jlContato1 = new javax.swing.JLabel();
        jtCargo = new javax.swing.JTextField();
        jlContato2 = new javax.swing.JLabel();
        jtDepartamento = new javax.swing.JTextField();
        jdcDataNascimentoFuncionario = new com.toedter.calendar.JDateChooser();

        jButton1.setText("jButton1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Funcionários");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbConsultar.setText("Consultar");
        jbConsultar.setEnabled(false);
        getContentPane().add(jbConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 120, 30));

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/loja/icones/accept.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.setEnabled(false);
        jbSalvar.setMaximumSize(new java.awt.Dimension(75, 23));
        jbSalvar.setMinimumSize(new java.awt.Dimension(75, 23));
        jbSalvar.setPreferredSize(new java.awt.Dimension(75, 23));
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jbSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 120, 30));

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/loja/icones/cancel.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.setEnabled(false);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jbCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 120, 30));

        jbExcluir.setText("Excluir");
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jbExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 120, 30));

        jbAlterar.setText("Alterar");
        jbAlterar.setEnabled(false);
        getContentPane().add(jbAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 120, 30));

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jbNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 120, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlCodigo.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlCodigo.setText("Código:");
        jPanel1.add(jlCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 70, -1));

        jlNome.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlNome.setText("Nome:");
        jPanel1.add(jlNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 70, -1));

        jtNome.setForeground(new java.awt.Color(0, 0, 204));
        jtNome.setToolTipText("Digite o nome");
        jtNome.setEnabled(false);
        jPanel1.add(jtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 240, -1));

        jlEmail.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlEmail.setText("E-mail:");
        jPanel1.add(jlEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, -1));

        jtEmail.setForeground(new java.awt.Color(0, 0, 204));
        jtEmail.setToolTipText("Digite o e-mail");
        jtEmail.setEnabled(false);
        jPanel1.add(jtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 240, -1));

        jtId.setText("0");
        jPanel1.add(jtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 20, -1));

        jtbTelefones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "DDD", "Telefone"
            }
        ));
        jScrollPane1.setViewportView(jtbTelefones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 480, 80));

        jbRetirar.setText("-");
        jPanel1.add(jbRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 40, -1));

        jlTelefones.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlTelefones.setText("Telefones:");
        jPanel1.add(jlTelefones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 70, -1));

        jcTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>", "Comercial", "Residencial", "Celular", "Recado" }));
        jcTipo.setEnabled(false);
        jPanel1.add(jcTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 310, -1));

        jtDDD.setForeground(new java.awt.Color(0, 0, 204));
        jtDDD.setToolTipText("");
        jtDDD.setEnabled(false);
        jPanel1.add(jtDDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 60, -1));

        jtTelefone.setForeground(new java.awt.Color(0, 0, 204));
        jtTelefone.setToolTipText("");
        jtTelefone.setEnabled(false);
        jPanel1.add(jtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 220, -1));

        jbAdicionar.setText("+");
        jPanel1.add(jbAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 40, -1));

        jlEmail2.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlEmail2.setText("Endereço:");
        jPanel1.add(jlEmail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 70, -1));

        jtEndereco.setForeground(new java.awt.Color(0, 0, 204));
        jtEndereco.setToolTipText("Digite o endereço");
        jtEndereco.setEnabled(false);
        jPanel1.add(jtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 240, -1));

        jlEmail3.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlEmail3.setText("Bairro:");
        jPanel1.add(jlEmail3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 70, -1));

        jtBairro.setForeground(new java.awt.Color(0, 0, 204));
        jtBairro.setToolTipText("Digite o bairro");
        jtBairro.setEnabled(false);
        jPanel1.add(jtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 240, -1));

        jlEmail4.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlEmail4.setText("UF");
        jPanel1.add(jlEmail4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 70, -1));

        jtNumero.setForeground(new java.awt.Color(0, 0, 204));
        jtNumero.setToolTipText("Digite o número");
        jtNumero.setEnabled(false);
        jPanel1.add(jtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 60, -1));

        jlEmail5.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlEmail5.setText("Complemento:");
        jPanel1.add(jlEmail5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 100, -1));

        jtComplemento.setForeground(new java.awt.Color(0, 0, 204));
        jtComplemento.setToolTipText("");
        jtComplemento.setEnabled(false);
        jPanel1.add(jtComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 220, -1));

        jlDataCadastro.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlDataCadastro.setText("xx/xx/xxxx");
        jPanel1.add(jlDataCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 90, -1));

        jtCidade.setForeground(new java.awt.Color(0, 0, 204));
        jtCidade.setToolTipText("Digite a cidade");
        jtCidade.setEnabled(false);
        jPanel1.add(jtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 240, -1));

        try {
            jftCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCep.setToolTipText("Digite o CEP");
        jftCep.setEnabled(false);
        jPanel1.add(jftCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 110, -1));

        jlEmail7.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlEmail7.setText("Número:");
        jPanel1.add(jlEmail7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 70, -1));

        jlEmail8.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlEmail8.setText("CEP");
        jPanel1.add(jlEmail8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 70, -1));

        jcbUf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "SP", "RJ", "ES", " " }));
        jcbUf.setToolTipText("Selecione o UF");
        jcbUf.setEnabled(false);
        jPanel1.add(jcbUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 110, -1));

        jcbSituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo" }));
        jcbSituacao.setToolTipText("Selecione a situação");
        jcbSituacao.setEnabled(false);
        jPanel1.add(jcbSituacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 170, -1));

        jlEmail9.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlEmail9.setText("Cidade:");
        jPanel1.add(jlEmail9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 70, -1));

        jlEmail10.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlEmail10.setText("Situação:");
        jPanel1.add(jlEmail10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 70, -1));

        jlEmail11.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlEmail11.setText("Cadastrado em:");
        jPanel1.add(jlEmail11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 100, -1));

        jTabbedPane1.addTab("Dados Gerais", jPanel1);

        jPanel2.setLayout(null);

        jtCTPS.setForeground(new java.awt.Color(0, 0, 204));
        jtCTPS.setToolTipText("Digite a CTPS do Funcionário");
        jtCTPS.setEnabled(false);
        jPanel2.add(jtCTPS);
        jtCTPS.setBounds(120, 140, 270, 20);

        jlContato.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlContato.setText("CTPS:");
        jPanel2.add(jlContato);
        jlContato.setBounds(60, 140, 70, 17);

        jlEmail1.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlEmail1.setText("Senha:");
        jPanel2.add(jlEmail1);
        jlEmail1.setBounds(120, 260, 70, 17);

        jpfSenha.setToolTipText("Digite a senha do Funcionário");
        jpfSenha.setEnabled(false);
        jPanel2.add(jpfSenha);
        jpfSenha.setBounds(200, 260, 160, 20);

        jlCnpj4.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlCnpj4.setText("RG:");
        jPanel2.add(jlCnpj4);
        jlCnpj4.setBounds(60, 70, 70, 17);

        jtRGFuncionario.setForeground(new java.awt.Color(0, 0, 204));
        jtRGFuncionario.setToolTipText("Digite o RG do Funcionário");
        jtRGFuncionario.setEnabled(false);
        jPanel2.add(jtRGFuncionario);
        jtRGFuncionario.setBounds(120, 70, 120, 20);

        jlIe7.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlIe7.setText("CPF:");
        jPanel2.add(jlIe7);
        jlIe7.setBounds(250, 70, 70, 17);

        try {
            jftCPFFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCPFFuncionario.setToolTipText("Digite o CPF do Funcionário");
        jftCPFFuncionario.setEnabled(false);
        jPanel2.add(jftCPFFuncionario);
        jftCPFFuncionario.setBounds(310, 70, 120, 20);

        jlIe4.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlIe4.setText("Data de Nascimento:");
        jPanel2.add(jlIe4);
        jlIe4.setBounds(60, 110, 160, 17);

        jlContato1.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlContato1.setText("Cargo:");
        jPanel2.add(jlContato1);
        jlContato1.setBounds(60, 170, 70, 17);

        jtCargo.setForeground(new java.awt.Color(0, 0, 204));
        jtCargo.setToolTipText("Digite o cargo do Funcionário");
        jtCargo.setEnabled(false);
        jPanel2.add(jtCargo);
        jtCargo.setBounds(120, 170, 270, 20);

        jlContato2.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlContato2.setText("Departamento:");
        jlContato2.setToolTipText("");
        jPanel2.add(jlContato2);
        jlContato2.setBounds(60, 200, 100, 17);

        jtDepartamento.setForeground(new java.awt.Color(0, 0, 204));
        jtDepartamento.setToolTipText("Digite o Departamento do Funcionário");
        jtDepartamento.setEnabled(false);
        jPanel2.add(jtDepartamento);
        jtDepartamento.setBounds(170, 200, 220, 20);

        jdcDataNascimentoFuncionario.setEnabled(false);
        jPanel2.add(jdcDataNascimentoFuncionario);
        jdcDataNascimentoFuncionario.setBounds(210, 110, 180, 20);

        jTabbedPane1.addTab("Dados do Funcionário", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 530, 470));

        setBounds(0, 0, 596, 610);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
    try{
        if(br.pro.luciene.ProjetoVendas.extras.
                Validacao.validarCampos(this)){
                    if(preencherObjeto()){
                        if(DAO.incluir(objCli)){
                            JOptionPane.showMessageDialog(this, "Cliente salvo !");
                            jbCancelarActionPerformed(evt);
                        } else {
                            throw new Exception("Erro ao incluir (DAO)");
                        }
                    }
                }
            
    }catch(Exception erro){
        JOptionPane.showMessageDialog(this, "Erro ao salvar:"+
                erro.getMessage());
        erro.printStackTrace();
    }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        br.pro.luciene.ProjetoVendas.extras.Validacao.limparCampos(this);
        br.pro.luciene.ProjetoVendas.extras.Validacao.tratarCampos(this, false);
        jbSalvar.setEnabled(false);
        jbCancelar.setEnabled(false);
        jbNovo.setEnabled(true);
        jbAlterar.setEnabled(false);
        jbExcluir.setEnabled(false);
// TODO add your handling code here:
}//GEN-LAST:event_jbCancelarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jbExcluirActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        br.pro.luciene.ProjetoVendas.extras.Validacao.limparCampos(this);
        br.pro.luciene.ProjetoVendas.extras.Validacao.tratarCampos(this, true);
        jbSalvar.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbNovo.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbAlterar.setEnabled(false);

}//GEN-LAST:event_jbNovoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbAdicionar;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbConsultar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbRetirar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox jcTipo;
    private javax.swing.JComboBox jcbSituacao;
    private javax.swing.JComboBox jcbUf;
    private com.toedter.calendar.JDateChooser jdcDataNascimentoFuncionario;
    private javax.swing.JFormattedTextField jftCPFFuncionario;
    private javax.swing.JFormattedTextField jftCep;
    private javax.swing.JLabel jlCnpj4;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlContato;
    private javax.swing.JLabel jlContato1;
    private javax.swing.JLabel jlContato2;
    private javax.swing.JLabel jlDataCadastro;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlEmail1;
    private javax.swing.JLabel jlEmail10;
    private javax.swing.JLabel jlEmail11;
    private javax.swing.JLabel jlEmail2;
    private javax.swing.JLabel jlEmail3;
    private javax.swing.JLabel jlEmail4;
    private javax.swing.JLabel jlEmail5;
    private javax.swing.JLabel jlEmail7;
    private javax.swing.JLabel jlEmail8;
    private javax.swing.JLabel jlEmail9;
    private javax.swing.JLabel jlIe4;
    private javax.swing.JLabel jlIe7;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlTelefones;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtBairro;
    private javax.swing.JTextField jtCTPS;
    private javax.swing.JTextField jtCargo;
    private javax.swing.JTextField jtCidade;
    private javax.swing.JTextField jtComplemento;
    private javax.swing.JTextField jtDDD;
    private javax.swing.JTextField jtDepartamento;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtEndereco;
    private javax.swing.JLabel jtId;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNumero;
    private javax.swing.JTextField jtRGFuncionario;
    private javax.swing.JTextField jtTelefone;
    private javax.swing.JTable jtbTelefones;
    // End of variables declaration//GEN-END:variables
   
    private void formataTabela() {

        jtbTelefones.getColumnModel().getColumn( 0 ).setPreferredWidth( 80 );
        jtbTelefones.getColumnModel().getColumn( 1 ).setPreferredWidth( 150 );
        jtbTelefones.getColumnModel().getColumn( 2 ).setPreferredWidth( 80 );

    }
    
//    public boolean validar_campos(){
//        if(jtCodigo.getText().equals("")){
//            JOptionPane.showMessageDialog(this,
//                    "Digite o campo código",
//                    "Validação", JOptionPane.ERROR_MESSAGE);
//            jtCodigo.requestFocus();
//            return false;
//        }
//        if(jtNome.getText().equals("")){
//            JOptionPane.showMessageDialog(this,
//                    "Digite o campo nome",
//                    "Validação", JOptionPane.ERROR_MESSAGE);
//            jtNome.requestFocus();
//            return false;
//        }
//        if(jtEmail.getText().equals("")){
//            JOptionPane.showMessageDialog(this,
//                    "Digite o campo e-mail",
//                    "Validação", JOptionPane.ERROR_MESSAGE);
//            jtEmail.requestFocus();
//            return false;
//        }
//        if(!jrFisica.isSelected() && !jrJuridica.isSelected()){
//            JOptionPane.showMessageDialog(this,
//                        "Selecione o Tipo de Pessoa",
//                        "Validação", JOptionPane.ERROR_MESSAGE);
//            return false;
//        }
//        else
//        {
//            if (jrFisica.isSelected()){
//                if(jtRg.getText().equals("")){
//                    JOptionPane.showMessageDialog(this,
//                            "Digite o campo RG",
//                            "Validação", JOptionPane.ERROR_MESSAGE);
//                    jtRg.requestFocus();
//                    return false;
//                }
//                if(jtCpf.getText().equals("")){
//                    JOptionPane.showMessageDialog(this,
//                            "Digite o campo CPF",
//                            "Validação", JOptionPane.ERROR_MESSAGE);
//                    jtCpf.requestFocus();
//                    return false;
//                }
//            }
//            if(jrJuridica.isSelected()){
//                if(jtCnpj.getText().equals("")){
//                    JOptionPane.showMessageDialog(this,
//                            "Digite o campo CNPJ",
//                            "Validação", JOptionPane.ERROR_MESSAGE);
//                    jtCnpj.requestFocus();
//                    return false;
//                }
//                if(jtIe.getText().equals("")){
//                    JOptionPane.showMessageDialog(this,
//                            "Digite o campo IE",
//                            "Validação", JOptionPane.ERROR_MESSAGE);
//                    jtIe.requestFocus();
//                    return false;
//                }
//            }
//        }
//        return true;
//    }

public boolean preencherObjeto() throws Exception{
    objFun.setIdPessoa(Integer.parseInt(jtId.getText()));
    objFun.setNome(jtNome.getText());
    objFun.setBairro(jtBairro.getText());
    objFun.setCep(jftCep.getText());
    objFun.setCidade(jtCidade.getText());
    objFun.setComplemento(jtComplemento.getText());
    objFun.setDataCadastro(new Timestamp(0));//-->
    objFun.setEmail(jtEmail.getText());
    objFun.setEndereco(jtEndereco.getText());
    objFun.setNumero(jtNumero.getText());
    objFun.setUf(jcbUf.getSelectedItem().toString());
    objFun.setSituacao(vetorSituacoes.get(jcbSituacao.getSelectedIndex()));
    for (int i=0; i<jtbTelefones.getRowCount(); i++){
        Telefone objTel = new Telefone();
        objTel.setDdd(jtbTelefones.getModel().getValueAt(i, 1).toString());
        objTel.setTelefone(jtbTelefones.getModel().getValueAt(i, 2).toString());
        objTel.setTipo(jtbTelefones.getModel().getValueAt(i, 0).toString());
        objFun.adicionarTelefone(objTel);
    } 
        objFun.setCTPS(jtCTPS.getText());
        objFun.setCargo(jtCargo.getText());
        objFun.setCpf(jftCPFFuncionario.getText());
        objFun.setRg(jtRGFuncionario.getText());
        objFun.setSenha(jpfSenha.getText());
    
    return true;
         
}
}
