/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pesquisa.java
 *
 * Created on 13/05/2009, 17:16:09
 */

package br.pro.luciene.ProjetoVendas.view;

import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import br.pro.luciene.ProjetoVendas.data.ProdutoData;

/**
 *
 * @author Diretor
 */
public class jifPesquisaGeral extends javax.swing.JInternalFrame {
    Vector cabecalho;
    /** Creates new form pesquisa */
    public jifPesquisaGeral() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_resultado = new javax.swing.JTable();
        tipo_pesquisa = new javax.swing.JPanel();
        jc_tabela = new javax.swing.JComboBox();
        jl_tabela = new javax.swing.JLabel();
        jl_argumento = new javax.swing.JLabel();
        jt_argumento = new javax.swing.JTextField();
        jb_pesquisar = new javax.swing.JButton();
        jl_qtderegistros = new javax.swing.JLabel();
        jl_resultado = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Pesquisa");
        getContentPane().setLayout(null);

        jtb_resultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Título 1", "Título 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtb_resultado);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 140, 570, 220);

        tipo_pesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo da Pesquisa"));

        jc_tabela.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Clientes", "Produtos", "Fornecedores", "Categorias" }));

        jl_tabela.setText("Escolha a tabela");

        jl_argumento.setText("Argumento de pesquisa");

        jb_pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/page_white_find.png"))); // NOI18N
        jb_pesquisar.setToolTipText("Pesquisar");
        jb_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_pesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tipo_pesquisaLayout = new javax.swing.GroupLayout(tipo_pesquisa);
        tipo_pesquisa.setLayout(tipo_pesquisaLayout);
        tipo_pesquisaLayout.setHorizontalGroup(
            tipo_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tipo_pesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tipo_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jc_tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(tipo_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_argumento, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tipo_pesquisaLayout.createSequentialGroup()
                        .addComponent(jt_argumento, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        tipo_pesquisaLayout.setVerticalGroup(
            tipo_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tipo_pesquisaLayout.createSequentialGroup()
                .addGroup(tipo_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tipo_pesquisaLayout.createSequentialGroup()
                        .addComponent(jl_tabela)
                        .addGap(5, 5, 5)
                        .addComponent(jc_tabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tipo_pesquisaLayout.createSequentialGroup()
                        .addComponent(jl_argumento)
                        .addGap(5, 5, 5)
                        .addGroup(tipo_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_pesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jt_argumento, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(tipo_pesquisa);
        tipo_pesquisa.setBounds(20, 20, 590, 80);

        jl_qtderegistros.setBackground(new java.awt.Color(0, 0, 204));
        jl_qtderegistros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_qtderegistros.setText("X Registros");
        getContentPane().add(jl_qtderegistros);
        jl_qtderegistros.setBounds(510, 120, 90, 20);

        jl_resultado.setBackground(new java.awt.Color(0, 0, 204));
        jl_resultado.setText("Resultado da pesquisa");
        getContentPane().add(jl_resultado);
        jl_resultado.setBounds(30, 120, 450, 20);

        setBounds(0, 0, 643, 424);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_pesquisarActionPerformed
     try {
        if (jc_tabela.getSelectedItem().toString().equals("Produtos")) {
            cabecalho = new Vector();
            ProdutoData objDAO = new ProdutoData();
            cabecalho.addElement("Código");
            cabecalho.addElement("Descrição");
            jtb_resultado.setModel(new DefaultTableModel(objDAO.pesquisar(jt_argumento.getText()), cabecalho));
            
        }

     } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao carregar a pesquisa ..." + ex.getMessage(), "Pesquisar",JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_jb_pesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_pesquisar;
    private javax.swing.JComboBox jc_tabela;
    private javax.swing.JLabel jl_argumento;
    private javax.swing.JLabel jl_qtderegistros;
    private javax.swing.JLabel jl_resultado;
    private javax.swing.JLabel jl_tabela;
    private javax.swing.JTextField jt_argumento;
    private javax.swing.JTable jtb_resultado;
    private javax.swing.JPanel tipo_pesquisa;
    // End of variables declaration//GEN-END:variables

}
