/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.edu.fatecriopreto.loja.view;

/**
 *
 * @author Luciene
 */
public class jfMedia extends javax.swing.JFrame {

    /**
     * Creates new form jfMedia
     */
    public jfMedia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNota1 = new javax.swing.JLabel();
        jtNota1 = new javax.swing.JTextField();
        jlNota2 = new javax.swing.JLabel();
        jtNota2 = new javax.swing.JTextField();
        jlNota3 = new javax.swing.JLabel();
        jtNota3 = new javax.swing.JTextField();
        jlNota4 = new javax.swing.JLabel();
        jtNota4 = new javax.swing.JTextField();
        jlMedia1 = new javax.swing.JLabel();
        jlMedia2 = new javax.swing.JLabel();
        jbLimpar = new javax.swing.JButton();
        jbCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculando a média");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlNota1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlNota1.setText("Nota 1");
        getContentPane().add(jlNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 53, -1, -1));
        getContentPane().add(jtNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 55, 120, -1));

        jlNota2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlNota2.setText("Nota 2");
        getContentPane().add(jlNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 93, -1, -1));

        jtNota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNota2ActionPerformed(evt);
            }
        });
        getContentPane().add(jtNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 97, 120, -1));

        jlNota3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlNota3.setText("Nota 3");
        getContentPane().add(jlNota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 135, -1, -1));
        getContentPane().add(jtNota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 137, 120, -1));

        jlNota4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlNota4.setText("Nota 4");
        getContentPane().add(jlNota4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 175, -1, -1));

        jtNota4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNota4ActionPerformed(evt);
            }
        });
        getContentPane().add(jtNota4, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 179, 120, -1));

        jlMedia1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlMedia1.setText("Média");
        getContentPane().add(jlMedia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 246, -1, -1));

        jlMedia2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jlMedia2.setText("0");
        getContentPane().add(jlMedia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 246, 95, -1));

        jbLimpar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbLimpar.setForeground(new java.awt.Color(0, 102, 0));
        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jbLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 53, 129, -1));

        jbCalcular.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbCalcular.setForeground(new java.awt.Color(204, 0, 0));
        jbCalcular.setText("Calcular");
        jbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(jbCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 108, -1, -1));

        setBounds(0, 0, 538, 340);
    }// </editor-fold>//GEN-END:initComponents

    private void jtNota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNota2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNota2ActionPerformed

    private void jtNota4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNota4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNota4ActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        jtNota1.setText("");
        jtNota2.setText("");
        jtNota3.setText("");
        jtNota4.setText("");
        jlMedia2.setText("0");
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcularActionPerformed
        float nota1,nota2, nota3, nota4,media;
        nota1 = Float.parseFloat(jtNota1.getText());
        nota2 = Float.parseFloat(jtNota2.getText());
        nota3 = Float.parseFloat(jtNota3.getText());
        nota4 = Float.parseFloat(jtNota4.getText());
        media = (nota1+nota2+nota3+nota4)/4;
        jlMedia2.setText(""+media);
    }//GEN-LAST:event_jbCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfMedia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCalcular;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlMedia1;
    private javax.swing.JLabel jlMedia2;
    private javax.swing.JLabel jlNota1;
    private javax.swing.JLabel jlNota2;
    private javax.swing.JLabel jlNota3;
    private javax.swing.JLabel jlNota4;
    private javax.swing.JTextField jtNota1;
    private javax.swing.JTextField jtNota2;
    private javax.swing.JTextField jtNota3;
    private javax.swing.JTextField jtNota4;
    // End of variables declaration//GEN-END:variables
}
