/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jifPessoas.java
 *
 * Created on 02/04/2009, 19:33:36
 */

package br.edu.fatecriopreto.loja.view;


import br.edu.fatecriopreto.loja.data.PessoaData;
import br.edu.fatecriopreto.loja.data.SituacaoData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import br.edu.fatecriopreto.loja.model.Cliente;
import br.edu.fatecriopreto.loja.model.Fornecedor;
import br.edu.fatecriopreto.loja.model.Funcionario;
import br.edu.fatecriopreto.loja.model.Pessoa;
import br.edu.fatecriopreto.loja.model.Situacao;
import br.edu.fatecriopreto.loja.model.Telefone;
import java.sql.Timestamp;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Diretor
 */
public class jifPessoas extends javax.swing.JInternalFrame {
    Cliente objCli;
    Funcionario objFun;
    Fornecedor objForn;
    Vector <Telefone> vetortelefones;
    Vector <Situacao> vetorSituacoes;
    PessoaData DAO;
    SituacaoData DAOSituacao;
    Vector cabecalho;
    /** Creates new form jifPessoas */
    public jifPessoas() {
        initComponents();
        try {
            objCli = new Cliente();
            objFun = new Funcionario();
            objForn=new Fornecedor();
            vetortelefones = new Vector<Telefone>();
            vetorSituacoes = new Vector<Situacao>();
            cabecalho = new Vector(); //JTable Pesquisa
            DAO = new PessoaData();
            DAOSituacao = new SituacaoData();
            vetorSituacoes = DAOSituacao.carregarCombo();
            jcbSituacao.setModel(new 
                DefaultComboBoxModel(vetorSituacoes));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "Erro ao abrir: " +
                    e.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jbConsultar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jpPessoa = new javax.swing.JPanel();
        jlCodigo = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jlEmail = new javax.swing.JLabel();
        jtEmail = new javax.swing.JTextField();
        jtId = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbTelefones = new javax.swing.JTable();
        jbRetirar = new javax.swing.JButton();
        jlTelefones = new javax.swing.JLabel();
        jcTipo = new javax.swing.JComboBox();
        jtDDD = new javax.swing.JTextField();
        jtTelefone = new javax.swing.JTextField();
        jbAdicionar = new javax.swing.JButton();
        jlEmail2 = new javax.swing.JLabel();
        jtEndereco = new javax.swing.JTextField();
        jlEmail3 = new javax.swing.JLabel();
        jtBairro = new javax.swing.JTextField();
        jlEmail4 = new javax.swing.JLabel();
        jtNumero = new javax.swing.JTextField();
        jlEmail5 = new javax.swing.JLabel();
        jtComplemento = new javax.swing.JTextField();
        jlEmail6 = new javax.swing.JLabel();
        jtCidade = new javax.swing.JTextField();
        jftCep = new javax.swing.JFormattedTextField();
        jlEmail7 = new javax.swing.JLabel();
        jlEmail8 = new javax.swing.JLabel();
        jcbUf = new javax.swing.JComboBox();
        jcbSituacao = new javax.swing.JComboBox();
        jlEmail9 = new javax.swing.JLabel();
        jlEmail10 = new javax.swing.JLabel();
        jlEmail11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        painelPessoas = new javax.swing.JTabbedPane();
        jpCliente = new javax.swing.JPanel();
        jtRGCliente = new javax.swing.JTextField();
        jlCnpj1 = new javax.swing.JLabel();
        jlIe1 = new javax.swing.JLabel();
        jtEmpresa = new javax.swing.JTextField();
        jlIe5 = new javax.swing.JLabel();
        jlIe6 = new javax.swing.JLabel();
        jftCpfCliente = new javax.swing.JFormattedTextField();
        jdcDataNascimentoCliente = new com.toedter.calendar.JDateChooser();
        jpFornecedor = new javax.swing.JPanel();
        jtIE = new javax.swing.JTextField();
        jlIe2 = new javax.swing.JLabel();
        jlCnpj2 = new javax.swing.JLabel();
        jlCnpj3 = new javax.swing.JLabel();
        jtMatricula = new javax.swing.JTextField();
        jlIe3 = new javax.swing.JLabel();
        jtVendedor = new javax.swing.JTextField();
        jftCNPJ = new javax.swing.JFormattedTextField();
        jpFuncionario = new javax.swing.JPanel();
        jtCTPS = new javax.swing.JTextField();
        jlContato = new javax.swing.JLabel();
        jlEmail1 = new javax.swing.JLabel();
        jpfSenha = new javax.swing.JPasswordField();
        jlCnpj4 = new javax.swing.JLabel();
        jtRGFuncionario = new javax.swing.JTextField();
        jlIe7 = new javax.swing.JLabel();
        jftCPFFuncionario = new javax.swing.JFormattedTextField();
        jlIe4 = new javax.swing.JLabel();
        jlContato1 = new javax.swing.JLabel();
        jtCargo = new javax.swing.JTextField();
        jlContato2 = new javax.swing.JLabel();
        jtDepartamento = new javax.swing.JTextField();
        jdcDataNascimentoFuncionario = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        jcbCampoPesquisa = new javax.swing.JComboBox();
        jtPesquisa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbPesquisa = new javax.swing.JTable();

        jButton1.setText("jButton1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Pessoas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbConsultar.setText("Consultar");
        jbConsultar.setEnabled(false);
        getContentPane().add(jbConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 120, 30));

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/loja/icones/accept.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.setEnabled(false);
        jbSalvar.setMaximumSize(new java.awt.Dimension(75, 23));
        jbSalvar.setMinimumSize(new java.awt.Dimension(75, 23));
        jbSalvar.setPreferredSize(new java.awt.Dimension(75, 23));
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jbSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 120, 30));

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/loja/icones/cancel.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.setEnabled(false);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jbCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 120, 30));

        jbExcluir.setText("Excluir");
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jbExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 120, 30));

        jbAlterar.setText("Alterar");
        jbAlterar.setEnabled(false);
        getContentPane().add(jbAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 120, 30));

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jbNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 120, 30));

        jpPessoa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlCodigo.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlCodigo.setText("Código:");
        jpPessoa.add(jlCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 70, -1));

        jlNome.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlNome.setText("Nome:");
        jpPessoa.add(jlNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 70, -1));

        jtNome.setForeground(new java.awt.Color(0, 0, 204));
        jtNome.setToolTipText("Digite o nome");
        jtNome.setEnabled(false);
        jpPessoa.add(jtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 240, -1));

        jlEmail.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlEmail.setText("E-mail:");
        jpPessoa.add(jlEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, -1));

        jtEmail.setForeground(new java.awt.Color(0, 0, 204));
        jtEmail.setToolTipText("Digite o e-mail");
        jtEmail.setEnabled(false);
        jpPessoa.add(jtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 240, -1));

        jtId.setText("0");
        jpPessoa.add(jtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 20, -1));

        jtbTelefones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "DDD", "Telefone"
            }
        ));
        jScrollPane1.setViewportView(jtbTelefones);

        jpPessoa.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 480, 80));

        jbRetirar.setText("-");
        jbRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRetirarActionPerformed(evt);
            }
        });
        jpPessoa.add(jbRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 40, -1));

        jlTelefones.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlTelefones.setText("Telefones:");
        jpPessoa.add(jlTelefones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 70, -1));

        jcTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>", "Comercial", "Residencial", "Celular", "Recado" }));
        jcTipo.setEnabled(false);
        jpPessoa.add(jcTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 310, -1));

        jtDDD.setForeground(new java.awt.Color(0, 0, 204));
        jtDDD.setToolTipText("");
        jtDDD.setEnabled(false);
        jpPessoa.add(jtDDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 60, -1));

        jtTelefone.setForeground(new java.awt.Color(0, 0, 204));
        jtTelefone.setToolTipText("");
        jtTelefone.setEnabled(false);
        jpPessoa.add(jtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 220, -1));

        jbAdicionar.setText("+");
        jbAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarActionPerformed(evt);
            }
        });
        jpPessoa.add(jbAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 40, -1));

        jlEmail2.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlEmail2.setText("Endereço:");
        jpPessoa.add(jlEmail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 70, -1));

        jtEndereco.setForeground(new java.awt.Color(0, 0, 204));
        jtEndereco.setToolTipText("Digite o endereço");
        jtEndereco.setEnabled(false);
        jpPessoa.add(jtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 240, -1));

        jlEmail3.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlEmail3.setText("Bairro:");
        jpPessoa.add(jlEmail3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 70, -1));

        jtBairro.setForeground(new java.awt.Color(0, 0, 204));
        jtBairro.setToolTipText("Digite o bairro");
        jtBairro.setEnabled(false);
        jpPessoa.add(jtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 240, -1));

        jlEmail4.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlEmail4.setText("UF");
        jpPessoa.add(jlEmail4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 70, -1));

        jtNumero.setForeground(new java.awt.Color(0, 0, 204));
        jtNumero.setToolTipText("Digite o número");
        jtNumero.setEnabled(false);
        jpPessoa.add(jtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 60, -1));

        jlEmail5.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlEmail5.setText("Complemento:");
        jpPessoa.add(jlEmail5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 100, -1));

        jtComplemento.setForeground(new java.awt.Color(0, 0, 204));
        jtComplemento.setToolTipText("");
        jtComplemento.setEnabled(false);
        jpPessoa.add(jtComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 220, -1));

        jlEmail6.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlEmail6.setText("xx/xx/xxxx");
        jpPessoa.add(jlEmail6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 90, -1));

        jtCidade.setForeground(new java.awt.Color(0, 0, 204));
        jtCidade.setToolTipText("Digite a cidade");
        jtCidade.setEnabled(false);
        jpPessoa.add(jtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 240, -1));

        try {
            jftCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCep.setToolTipText("Digite o CEP");
        jftCep.setEnabled(false);
        jpPessoa.add(jftCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 110, -1));

        jlEmail7.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlEmail7.setText("Número:");
        jpPessoa.add(jlEmail7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 70, -1));

        jlEmail8.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlEmail8.setText("CEP");
        jpPessoa.add(jlEmail8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 70, -1));

        jcbUf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbUf.setToolTipText("Selecione o UF");
        jcbUf.setEnabled(false);
        jpPessoa.add(jcbUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 110, -1));

        jcbSituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbSituacao.setToolTipText("Selecione a situação");
        jcbSituacao.setEnabled(false);
        jpPessoa.add(jcbSituacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 170, -1));

        jlEmail9.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlEmail9.setText("Cidade:");
        jpPessoa.add(jlEmail9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 70, -1));

        jlEmail10.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlEmail10.setText("Situação:");
        jpPessoa.add(jlEmail10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 70, -1));

        jlEmail11.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlEmail11.setText("Cadastrado em:");
        jpPessoa.add(jlEmail11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 100, -1));

        jTabbedPane2.addTab("Pessoa", jpPessoa);

        jPanel6.setLayout(null);

        jpCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jpClienteFocusLost(evt);
            }
        });
        jpCliente.setLayout(null);

        jtRGCliente.setForeground(new java.awt.Color(0, 0, 204));
        jtRGCliente.setToolTipText("Digite o RG do Cliente");
        jtRGCliente.setEnabled(false);
        jpCliente.add(jtRGCliente);
        jtRGCliente.setBounds(140, 80, 120, 20);

        jlCnpj1.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlCnpj1.setText("RG:");
        jpCliente.add(jlCnpj1);
        jlCnpj1.setBounds(90, 80, 70, 17);

        jlIe1.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlIe1.setText("Nascimento:");
        jpCliente.add(jlIe1);
        jlIe1.setBounds(90, 160, 100, 17);

        jtEmpresa.setForeground(new java.awt.Color(0, 0, 204));
        jtEmpresa.setToolTipText("Digite a empresa do Cliente");
        jtEmpresa.setEnabled(false);
        jpCliente.add(jtEmpresa);
        jtEmpresa.setBounds(160, 200, 240, 20);

        jlIe5.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlIe5.setText("CPF:");
        jpCliente.add(jlIe5);
        jlIe5.setBounds(90, 120, 70, 17);

        jlIe6.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlIe6.setText("Empresa:");
        jpCliente.add(jlIe6);
        jlIe6.setBounds(90, 200, 70, 17);

        try {
            jftCpfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCpfCliente.setToolTipText("Digite o CPF do Cliente");
        jftCpfCliente.setEnabled(false);
        jpCliente.add(jftCpfCliente);
        jftCpfCliente.setBounds(140, 120, 120, 20);

        jdcDataNascimentoCliente.setEnabled(false);
        jpCliente.add(jdcDataNascimentoCliente);
        jdcDataNascimentoCliente.setBounds(180, 160, 180, 20);

        painelPessoas.addTab("Cliente", jpCliente);

        jpFornecedor.setLayout(null);

        jtIE.setForeground(new java.awt.Color(0, 0, 204));
        jtIE.setToolTipText("Digite a Inscrição Estadual do Fornecedor");
        jtIE.setEnabled(false);
        jpFornecedor.add(jtIE);
        jtIE.setBounds(120, 130, 200, 20);

        jlIe2.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlIe2.setText("IE:");
        jpFornecedor.add(jlIe2);
        jlIe2.setBounds(70, 130, 70, 17);

        jlCnpj2.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlCnpj2.setText("CPNJ:");
        jpFornecedor.add(jlCnpj2);
        jlCnpj2.setBounds(70, 100, 70, 17);

        jlCnpj3.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlCnpj3.setText("Matrícula:");
        jpFornecedor.add(jlCnpj3);
        jlCnpj3.setBounds(70, 160, 70, 17);

        jtMatricula.setForeground(new java.awt.Color(0, 0, 204));
        jtMatricula.setToolTipText("Digite a matrícula do Fornecedor");
        jtMatricula.setEnabled(false);
        jpFornecedor.add(jtMatricula);
        jtMatricula.setBounds(150, 160, 260, 20);

        jlIe3.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlIe3.setText("Vendedor");
        jpFornecedor.add(jlIe3);
        jlIe3.setBounds(70, 190, 70, 17);

        jtVendedor.setForeground(new java.awt.Color(0, 0, 204));
        jtVendedor.setToolTipText("Digite o nome do Fornecedor");
        jtVendedor.setEnabled(false);
        jpFornecedor.add(jtVendedor);
        jtVendedor.setBounds(150, 190, 260, 20);

        try {
            jftCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCNPJ.setToolTipText("Digite o CNPJ do Fornecedor");
        jftCNPJ.setEnabled(false);
        jpFornecedor.add(jftCNPJ);
        jftCNPJ.setBounds(120, 100, 200, 20);

        painelPessoas.addTab("Fornecedor", jpFornecedor);

        jpFuncionario.setLayout(null);

        jtCTPS.setForeground(new java.awt.Color(0, 0, 204));
        jtCTPS.setToolTipText("Digite a CTPS do Funcionário");
        jtCTPS.setEnabled(false);
        jpFuncionario.add(jtCTPS);
        jtCTPS.setBounds(120, 140, 270, 20);

        jlContato.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlContato.setText("CTPS:");
        jpFuncionario.add(jlContato);
        jlContato.setBounds(60, 140, 70, 17);

        jlEmail1.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlEmail1.setText("Senha:");
        jpFuncionario.add(jlEmail1);
        jlEmail1.setBounds(120, 260, 70, 17);

        jpfSenha.setToolTipText("Digite a senha do Funcionário");
        jpfSenha.setEnabled(false);
        jpFuncionario.add(jpfSenha);
        jpfSenha.setBounds(200, 260, 160, 20);

        jlCnpj4.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlCnpj4.setText("RG:");
        jpFuncionario.add(jlCnpj4);
        jlCnpj4.setBounds(60, 70, 70, 17);

        jtRGFuncionario.setForeground(new java.awt.Color(0, 0, 204));
        jtRGFuncionario.setToolTipText("Digite o RG do Funcionário");
        jtRGFuncionario.setEnabled(false);
        jpFuncionario.add(jtRGFuncionario);
        jtRGFuncionario.setBounds(120, 70, 120, 20);

        jlIe7.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlIe7.setText("CPF:");
        jpFuncionario.add(jlIe7);
        jlIe7.setBounds(250, 70, 70, 17);

        try {
            jftCPFFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCPFFuncionario.setToolTipText("Digite o CPF do Funcionário");
        jftCPFFuncionario.setEnabled(false);
        jpFuncionario.add(jftCPFFuncionario);
        jftCPFFuncionario.setBounds(310, 70, 120, 20);

        jlIe4.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlIe4.setText("Data de Nascimento:");
        jpFuncionario.add(jlIe4);
        jlIe4.setBounds(60, 110, 160, 17);

        jlContato1.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlContato1.setText("Cargo:");
        jpFuncionario.add(jlContato1);
        jlContato1.setBounds(60, 170, 70, 17);

        jtCargo.setForeground(new java.awt.Color(0, 0, 204));
        jtCargo.setToolTipText("Digite o cargo do Funcionário");
        jtCargo.setEnabled(false);
        jpFuncionario.add(jtCargo);
        jtCargo.setBounds(120, 170, 270, 20);

        jlContato2.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jlContato2.setText("Departamento:");
        jlContato2.setToolTipText("");
        jpFuncionario.add(jlContato2);
        jlContato2.setBounds(60, 200, 100, 17);

        jtDepartamento.setForeground(new java.awt.Color(0, 0, 204));
        jtDepartamento.setToolTipText("Digite o Departamento do Funcionário");
        jtDepartamento.setEnabled(false);
        jpFuncionario.add(jtDepartamento);
        jtDepartamento.setBounds(170, 200, 220, 20);

        jdcDataNascimentoFuncionario.setEnabled(false);
        jpFuncionario.add(jdcDataNascimentoFuncionario);
        jdcDataNascimentoFuncionario.setBounds(210, 110, 180, 20);

        painelPessoas.addTab("Funcionário", jpFuncionario);

        jPanel6.add(painelPessoas);
        painelPessoas.setBounds(20, 20, 500, 400);
        painelPessoas.getAccessibleContext().setAccessibleName("Jurídica");

        jTabbedPane2.addTab("Tipo Pessoa", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcbCampoPesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "id", "Nome", "CPF", "CNPJ", "Nome do Vendedor", "Telefone" }));
        jcbCampoPesquisa.setToolTipText("");
        jPanel7.add(jcbCampoPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 120, -1));

        jtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesquisaKeyReleased(evt);
            }
        });
        jPanel7.add(jtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 350, -1));

        jLabel1.setText("Campo");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setText("Pesquisa");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jtbPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jtbPesquisa);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 100, 490, 320));

        jTabbedPane2.addTab("Pesquisa", jPanel7);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 480));

        setBounds(0, 0, 584, 610);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
    try{
        if(br.edu.fatecriopreto.loja.extras.
                Validacao.validarCampos(jpPessoa.getComponents())){
            if(painelPessoas.getSelectedIndex()==0){//cliente
                if(br.edu.fatecriopreto.loja.extras.
                    Validacao.validarCampos(jpCliente.getComponents())){
                    if(preencherObjeto()){
                        if(DAO.incluir(objCli)){
                            JOptionPane.showMessageDialog(this, "Cliente salvo !");
                            jbCancelarActionPerformed(evt);
                        } else {
                            throw new Exception("Erro ao incluir (DAO)");
                        }
                    }
                }
            }
            if(painelPessoas.getSelectedIndex()==1){//fornecedor
                if(br.edu.fatecriopreto.loja.extras.
                    Validacao.validarCampos(jpFornecedor.getComponents())){
                    if(preencherObjeto()){
                        if(DAO.incluir(objForn)){
                            JOptionPane.showMessageDialog(this, "Fornecedor salvo !");
                            jbCancelarActionPerformed(evt);
                        } else {
                            throw new Exception("Erro ao incluir (DAO)");
                        }
                    }
                }
            }
            if(painelPessoas.getSelectedIndex()==2){//funcionario
                if(br.edu.fatecriopreto.loja.extras.
                    Validacao.validarCampos(jpFuncionario.getComponents())){
                    if(preencherObjeto()){
                        if(DAO.incluir(objFun)){
                            JOptionPane.showMessageDialog(this, "Funcionário salvo !");
                            jbCancelarActionPerformed(evt);
                        } else {
                            throw new Exception("Erro ao incluir (DAO)");
                        }
                    } //preencher objeto
                } //validar campos de funcionário
            }//painel de funcionario selecionado
        }//validar campos de pessoa 
    }catch(Exception erro){
        JOptionPane.showMessageDialog(this, "Erro ao salvar:"+
                erro.getMessage());
        erro.printStackTrace();
    }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        br.edu.fatecriopreto.loja.extras.Validacao.limparCampos(this);
        br.edu.fatecriopreto.loja.extras.Validacao.tratarCampos(this, false);
        jbSalvar.setEnabled(false);
        jbCancelar.setEnabled(false);
        jbNovo.setEnabled(true);
        jbAlterar.setEnabled(false);
        jbExcluir.setEnabled(false);
// TODO add your handling code here:
}//GEN-LAST:event_jbCancelarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jbExcluirActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        br.edu.fatecriopreto.loja.extras.Validacao.limparCampos(this);
        br.edu.fatecriopreto.loja.extras.Validacao.tratarCampos(this, true);
        jbSalvar.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbNovo.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbAlterar.setEnabled(false);

}//GEN-LAST:event_jbNovoActionPerformed

    private void jbRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRetirarActionPerformed
        DefaultTableModel mp = (DefaultTableModel) jtbTelefones.getModel();
        mp.removeRow(jtbTelefones.getSelectedRow());
        jtbTelefones.setModel(mp);
}//GEN-LAST:event_jbRetirarActionPerformed

    private void jbAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarActionPerformed
        DefaultTableModel mp = (DefaultTableModel) jtbTelefones.getModel();
        mp.addRow(new String[]{jcTipo.getSelectedItem().toString(),
        jtDDD.getText(),
        jtTelefone.getText()});
}//GEN-LAST:event_jbAdicionarActionPerformed

    private void jpClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpClienteFocusLost
        jtRGCliente.setText("");
        jftCpfCliente.setText("   .   .   -  ");
        jdcDataNascimentoCliente.setDate(null);
        jtEmpresa.setText("");
    }//GEN-LAST:event_jpClienteFocusLost

    private void jtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesquisaKeyReleased
        try {
            cabecalho = new Vector();
            cabecalho.add("idPessoa");  //coluna 0
            cabecalho.add("Nome"); // coluna 1
            if(jcbCampoPesquisa.getSelectedIndex()==0){//id   
                
            }
            if(jcbCampoPesquisa.getSelectedIndex()==1){//nome
               
            }
            if(jcbCampoPesquisa.getSelectedIndex()==2){//cpf
                cabecalho.add("CPF");
            }
            if(jcbCampoPesquisa.getSelectedIndex()==3){//cnpj
                cabecalho.add("CNPJ");
            }
            if(jcbCampoPesquisa.getSelectedIndex()==4){//nome vendedor
                cabecalho.add("Vendedor");
            }
            if(jcbCampoPesquisa.getSelectedIndex()==5){//telefone
                cabecalho.add("Telefone");
            }
            jtbPesquisa.setModel(new DefaultTableModel(
                    DAO.pesquisar(jcbCampoPesquisa.getSelectedIndex(),jtPesquisa.getText()),
                    cabecalho));
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro: "
                    + erro.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtPesquisaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton jbAdicionar;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbConsultar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbRetirar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox jcTipo;
    private javax.swing.JComboBox jcbCampoPesquisa;
    private javax.swing.JComboBox jcbSituacao;
    private javax.swing.JComboBox jcbUf;
    private com.toedter.calendar.JDateChooser jdcDataNascimentoCliente;
    private com.toedter.calendar.JDateChooser jdcDataNascimentoFuncionario;
    private javax.swing.JFormattedTextField jftCNPJ;
    private javax.swing.JFormattedTextField jftCPFFuncionario;
    private javax.swing.JFormattedTextField jftCep;
    private javax.swing.JFormattedTextField jftCpfCliente;
    private javax.swing.JLabel jlCnpj1;
    private javax.swing.JLabel jlCnpj2;
    private javax.swing.JLabel jlCnpj3;
    private javax.swing.JLabel jlCnpj4;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlContato;
    private javax.swing.JLabel jlContato1;
    private javax.swing.JLabel jlContato2;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlEmail1;
    private javax.swing.JLabel jlEmail10;
    private javax.swing.JLabel jlEmail11;
    private javax.swing.JLabel jlEmail2;
    private javax.swing.JLabel jlEmail3;
    private javax.swing.JLabel jlEmail4;
    private javax.swing.JLabel jlEmail5;
    private javax.swing.JLabel jlEmail6;
    private javax.swing.JLabel jlEmail7;
    private javax.swing.JLabel jlEmail8;
    private javax.swing.JLabel jlEmail9;
    private javax.swing.JLabel jlIe1;
    private javax.swing.JLabel jlIe2;
    private javax.swing.JLabel jlIe3;
    private javax.swing.JLabel jlIe4;
    private javax.swing.JLabel jlIe5;
    private javax.swing.JLabel jlIe6;
    private javax.swing.JLabel jlIe7;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlTelefones;
    private javax.swing.JPanel jpCliente;
    private javax.swing.JPanel jpFornecedor;
    private javax.swing.JPanel jpFuncionario;
    private javax.swing.JPanel jpPessoa;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtBairro;
    private javax.swing.JTextField jtCTPS;
    private javax.swing.JTextField jtCargo;
    private javax.swing.JTextField jtCidade;
    private javax.swing.JTextField jtComplemento;
    private javax.swing.JTextField jtDDD;
    private javax.swing.JTextField jtDepartamento;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtEmpresa;
    private javax.swing.JTextField jtEndereco;
    private javax.swing.JTextField jtIE;
    private javax.swing.JLabel jtId;
    private javax.swing.JTextField jtMatricula;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNumero;
    private javax.swing.JTextField jtPesquisa;
    private javax.swing.JTextField jtRGCliente;
    private javax.swing.JTextField jtRGFuncionario;
    private javax.swing.JTextField jtTelefone;
    private javax.swing.JTextField jtVendedor;
    private javax.swing.JTable jtbPesquisa;
    private javax.swing.JTable jtbTelefones;
    private javax.swing.JTabbedPane painelPessoas;
    // End of variables declaration//GEN-END:variables
   
    private void formataTabela() {

        jtbTelefones.getColumnModel().getColumn( 0 ).setPreferredWidth( 80 );
        jtbTelefones.getColumnModel().getColumn( 1 ).setPreferredWidth( 150 );
        jtbTelefones.getColumnModel().getColumn( 2 ).setPreferredWidth( 80 );

    }
    
//    public boolean validar_campos(){
//        if(jtCodigo.getText().equals("")){
//            JOptionPane.showMessageDialog(this,
//                    "Digite o campo código",
//                    "Validação", JOptionPane.ERROR_MESSAGE);
//            jtCodigo.requestFocus();
//            return false;
//        }
//        if(jtNome.getText().equals("")){
//            JOptionPane.showMessageDialog(this,
//                    "Digite o campo nome",
//                    "Validação", JOptionPane.ERROR_MESSAGE);
//            jtNome.requestFocus();
//            return false;
//        }
//        if(jtEmail.getText().equals("")){
//            JOptionPane.showMessageDialog(this,
//                    "Digite o campo e-mail",
//                    "Validação", JOptionPane.ERROR_MESSAGE);
//            jtEmail.requestFocus();
//            return false;
//        }
//        if(!jrFisica.isSelected() && !jrJuridica.isSelected()){
//            JOptionPane.showMessageDialog(this,
//                        "Selecione o Tipo de Pessoa",
//                        "Validação", JOptionPane.ERROR_MESSAGE);
//            return false;
//        }
//        else
//        {
//            if (jrFisica.isSelected()){
//                if(jtRg.getText().equals("")){
//                    JOptionPane.showMessageDialog(this,
//                            "Digite o campo RG",
//                            "Validação", JOptionPane.ERROR_MESSAGE);
//                    jtRg.requestFocus();
//                    return false;
//                }
//                if(jtCpf.getText().equals("")){
//                    JOptionPane.showMessageDialog(this,
//                            "Digite o campo CPF",
//                            "Validação", JOptionPane.ERROR_MESSAGE);
//                    jtCpf.requestFocus();
//                    return false;
//                }
//            }
//            if(jrJuridica.isSelected()){
//                if(jtCnpj.getText().equals("")){
//                    JOptionPane.showMessageDialog(this,
//                            "Digite o campo CNPJ",
//                            "Validação", JOptionPane.ERROR_MESSAGE);
//                    jtCnpj.requestFocus();
//                    return false;
//                }
//                if(jtIe.getText().equals("")){
//                    JOptionPane.showMessageDialog(this,
//                            "Digite o campo IE",
//                            "Validação", JOptionPane.ERROR_MESSAGE);
//                    jtIe.requestFocus();
//                    return false;
//                }
//            }
//        }
//        return true;
//    }

public boolean preencherObjeto() throws Exception{
    
    if(painelPessoas.getSelectedIndex()==0){//cliente
        preencherObjeto(objCli); //pessoa
        objCli.setCpf(jftCpfCliente.getText());
        objCli.setDataNascimento(new Timestamp(jdcDataNascimentoCliente.
                getDate().getTime()));
        objCli.setEmpresa(jtEmpresa.getText());
        objCli.setRg(jtRGCliente.getText());
    }
    if(painelPessoas.getSelectedIndex()==1){//fornecedor
        preencherObjeto(objForn);
        objForn.setIdMatricula(Integer.parseInt(jtMatricula.getText()));
        objForn.setNomeVendedor(jtVendedor.getText());
        objForn.setCnpj(jftCNPJ.getText());
        objForn.setIe(jtIE.getText());
    }
    if(painelPessoas.getSelectedIndex()==2){//funcionário
        preencherObjeto(objFun);
        objFun.setCTPS(jtCTPS.getText());
        objFun.setCargo(jtCargo.getText());
        objFun.setCpf(jftCPFFuncionario.getText());
        objFun.setRg(jtRGFuncionario.getText());
        objFun.setSenha(jpfSenha.getText());
    }
    return true;
         
}
private void preencherObjeto(Pessoa obj) throws Exception {
    obj.setIdPessoa(Integer.parseInt(jtId.getText()));
    obj.setNome(jtNome.getText());
    obj.setBairro(jtBairro.getText());
    obj.setCep(jftCep.getText());
    obj.setCidade(jtCidade.getText());
    obj.setComplemento(jtComplemento.getText());
    obj.setDataCadastro(new Timestamp(0));//-->
    obj.setEmail(jtEmail.getText());
    obj.setEndereco(jtEndereco.getText());
    obj.setNumero(jtNumero.getText());
    obj.setUf(jcbUf.getSelectedItem().toString());
    obj.setSituacao(vetorSituacoes.get(jcbSituacao.getSelectedIndex()));
    for (int i=0; i<jtbTelefones.getRowCount(); i++){
        Telefone objTel = new Telefone();
        objTel.setDdd(jtbTelefones.getModel().getValueAt(i, 1).toString());
        objTel.setTelefone(jtbTelefones.getModel().getValueAt(i, 2).toString());
        objTel.setTipo(jtbTelefones.getModel().getValueAt(i, 0).toString());
        obj.adicionarTelefone(objTel);
    }
}
}
