/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * splash.java
 *
 * Created on 13/05/2009, 14:04:38
 */

package br.edu.fatecriopreto.loja.view;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Diretor
 */
public class splash extends javax.swing.JWindow {

    /** Creates new form splash */
    public splash() {
        initComponents();
    }

        public void showSplash() {
        //JPanel
        conteudo = (JPanel)getContentPane();
        conteudo.setBackground(Color.white);
        barra_progresso.setStringPainted(true);

        // Configura a posição e o tamanho da janela
        int width = 800;
        int height =600;
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        //centralizar
        int x = (screen.width-width)/2;
        int y = (screen.height-height)/2;
        setBounds(x,y,width,height);

        // Torna visível
        setVisible(true);
        for(int i =0; i <= 100; i++) {
            try { Thread.sleep(150); } catch (Exception e) {}
            barra_progresso.setValue(barra_progresso.getValue()+1);
         }

        try { Thread.sleep(50); } catch (Exception e) {}
        new jfLogin().setVisible(true);
        this.dispose();
        // Espera ate que os recursos estejam carregados
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conteudo = new javax.swing.JPanel();
        jlLogo = new javax.swing.JLabel();
        barra_progresso = new javax.swing.JProgressBar();

        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        conteudo.setBackground(new java.awt.Color(255, 255, 255));
        conteudo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        conteudo.setMinimumSize(new java.awt.Dimension(800, 600));
        conteudo.setPreferredSize(new java.awt.Dimension(800, 600));
        conteudo.setLayout(null);

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatecriopreto/loja/imagens/logo.jpg"))); // NOI18N
        conteudo.add(jlLogo);
        jlLogo.setBounds(400, 300, 270, 130);
        conteudo.add(barra_progresso);
        barra_progresso.setBounds(30, 550, 740, 20);

        getContentPane().add(conteudo);
        conteudo.setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents


    public static void main(String[] args) {
        splash splash = new splash();
        splash.showSplash();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JProgressBar barra_progresso;
    private javax.swing.JPanel conteudo;
    private javax.swing.JLabel jlLogo;
    // End of variables declaration//GEN-END:variables

}
